name: "Release Dinky"

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Dinky version'
        required: true
      prerelease:
        type: boolean
        description: 'Is this a pre-release?'
        required: true
      release_notes:
        type: string
        description: 'Release notes'
        required: true

jobs:
  build:
    name: Build Flink ${{ matrix.flink }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        flink: ["1.20"]

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Dinky (Flink ${{ matrix.flink }})
        run: |
          ./mvnw -B clean package \
            -Dmaven.test.skip=false \
            -Dspotless.check.skip=true \
            -Denforcer.skip=false \
            -Dmaven.javadoc.skip=true \
            -Pprod,flink-single-version,flink-${{ matrix.flink }},maven-central,web,fast \
            --no-snapshot-updates

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dinky-release-${{ matrix.flink }}
          path: ./build/dinky-release-*.tar.gz


  release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./build

      - name: List files
        run: tree ./build

      - name: Create GitHub Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: ${{ inputs.prerelease }}
          draft: false
          title: "Dinky ${{ inputs.version }} Release"
          body: |
            ${{ inputs.release_notes }}
          files: |
            ./build/**/dinky-release-*.tar.gz
